version: '3.4'

services:
  testnhibernate:
    image: ${DOCKER_REGISTRY-}testnhibernate
    ports:
      - 5000:80
    links:
      - sql.data
    build:
      context: .
      dockerfile: TestNHibernate/Dockerfile
  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Volodymyr@10091984
      - ACCEPT_EULA=Y
    container_name: mssql_db
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
  rabbitMQ:
    image: rabbitmq:3.9.11-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
volumes:
  dbdata:
    driver: local